version: '3'

services:
    app:
        build:
            context: .
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - my_network

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: jokitugas
            MYSQL_DATABASE: jokitugasweb
            MYSQL_USER: jokitugas
            MYSQL_PASSWORD: jokitugas
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - my_network

networks:
    my_network:
        driver: bridge

volumes:
    mysql_data:
